module.exports = {
    //local storage id
    LOGIN_USER_ID: 'LOGIN_USER_ID',
    LOGIN_PASSWORD: 'LOGIN_PASSWORD',
    LOGIN_AUTO_LOGIN: 'LOGIN_AUTO_LOGIN',
    MESSAGE_BADGES: 'MESSAGE_BADGES',
    GROUP_MESSAGE_BADGES: 'GROUP_MESSAGE_BADGES',
    GROUP_CHAT_AT_NUMBERS: 'GROUP_CHAT_AT_NUMBERS',
    US_NOT_PLAY_SOUND: 'US_NOT_PLAY_SOUND',
    //notify message id
    MESSAGE_NOTIFY_ID: 1001,
    UNKOWN:'UNKOWN'
};
