module.exports = {
	// app
	'main': require('./home/main'),
	'button': require('./common/button'),
	'colorThemes': require('./common/colorThemes'),
  	//common
	'virtualList': require('./common/virtualList'),
	'list': require('./common/list'),
	'medialist': require('./common/mediaList'),
	'lazyLoad': require('./common/lazyLoad'),
	'grid': require('./common/grid'),
	'chip': require('./common/chip'),
	'upscroller': require('./common/upscroller'),
	'floatingButton': require('./common/floatingButton'),
	'staticFloatingButton': require('./common/staticFloatingButton'),
	'dialFloatingButton': require('./common/dialFloatingButton'),
	'popoverFloatingButton': require('./common/popoverFloatingButton'),
	'radioCheckBox': require('./common/radioCheckBox'),
	'form': require('./common/form.js'),
	'progressBar': require('./common/progressBar.js'),
	'picker': require('./common/picker.js'),
	'cityPicker': require('./common/cityPicker.js'),
	'popover': require('./common/popover.js'),
	'modals': require('./common/modals'),
	'preloader': require('./common/preloader'),
	'calendar': require('./common/calendar'),
	'tabs': require('./common/tabs'),
	'tabsSwipeable': require('./common/tabsSwipeable'),
	'tabsStatic': require('./common/tabsStatic'),
	'tabsAnimated': require('./common/tabsAnimated'),
	'notifications': require('./common/notifications'),
	'panels': require('./common/panels'),
	'panels3d': require('./common/3dpanels'),
	'search': require('./common/search'),
	'cards': require('./common/cards'),
	'pullToRefresh': require('./common/pullToRefresh'),
	'infiniteScroll': require('./common/infiniteScroll'),
	'accordion': require('./common/accordion'),
	'autocomplete':require('./common/autocomplete'),
	'toast': require('./common/toast'),
	'sortableList': require('./common/sortableList'),
	'swipeDelete': require('./common/swipeDelete'),
	'barsHideOnScroll': require('./common/barsHideOnScroll'),
	'subbarsHideOnScroll': require('./common/subbarsHideOnScroll'),
	//params
	'page1': require('./params/page1'),
	'page2': require('./params/page2'),
	'page3': require('./params/page3'),
	'page4': require('./params/page4'),
	'page5': require('./params/page5'),
	'page6': require('./params/page6'),
	//swiper
	'swiper': require('./swiper/swiper'),
	'swiperHorizontal': require('./swiper/swiperHorizontal'),
	'swiperVertical': require('./swiper/swiperVertical'),
	'swiperSpaceBetween': require('./swiper/swiperSpaceBetween'),
	'swiperMultiple': require('./swiper/swiperMultiple'),
	'swiperNested': require('./swiper/swiperNested'),
	'swiperLoop': require('./swiper/swiperLoop'),
	'swiper3dCube': require('./swiper/swiper3dCube'),
	'swiper3dCoverflow': require('./swiper/swiper3dCoverflow'),
	'swiper3dFlip': require('./swiper/swiper3dFlip'),
	'swiperFade': require('./swiper/swiperFade'),
	'swiperScrollbar': require('./swiper/swiperScrollbar'),
	'swiperGallery': require('./swiper/swiperGallery'),
	'swiperCustom': require('./swiper/swiperCustom'),
	'swiperParallax': require('./swiper/swiperParallax'),
	'swiperLazy': require('./swiper/swiperLazy'),
	'swiperProgressPagination': require('./swiper/swiperProgressPagination'),
	'swiperFractionPagination': require('./swiper/swiperFractionPagination'),
	//icons
	'icons': require('./common/icons')
};
