module.exports = {
	// app
	'home': require('./home/home'),
	'button': require('./common/button'),
  //list
	'list': require('./common/list'),
	'medialist': require('./common/mediaList'),
	'grid': require('./common/grid'),
	'radioCheckBox': require('./common/radioCheckBox'),
	'form': require('./common/form.js'),
	'picker': require('./common/picker.js'),
	'pickerEx': require('./common/pickerEx.js'),
	'popover': require('./common/popover.js'),
	'modals': require('./common/modals'),
	'preloader': require('./common/preloader'),
	'calendar': require('./common/calendar'),
	'tabs': require('./common/tabs'),
	'notifications': require('./common/notifications'),
	'panels': require('./common/panels'),
	'search': require('./common/search'),
	'cards': require('./common/cards'),
	'pullToRefresh': require('./common/pullToRefresh'),
	'infiniteScroll': require('./common/infiniteScroll'),
	'accordion': require('./common/accordion'),
	'toast': require('./common/toast'),
	'sortableList': require('./common/sortableList'),
	'swipeDelete': require('./common/swipeDelete'),
	'barsHideOnScroll': require('./common/barsHideOnScroll'),
	'subbarsHideOnScroll': require('./common/subbarsHideOnScroll'),
	//swiper
	'swiper': require('./swiper/swiper'),
	'swiperHorizontal': require('./swiper/swiperHorizontal'),
	'swiperVertical': require('./swiper/swiperVertical'),
	'swiperSpaceBetween': require('./swiper/swiperSpaceBetween'),
	'swiperMultiple': require('./swiper/swiperMultiple'),
	'swiperNested': require('./swiper/swiperNested'),
	'swiperLoop': require('./swiper/swiperLoop'),
	'swiper3dCube': require('./swiper/swiper3dCube'),
	'swiper3dCoverflow': require('./swiper/swiper3dCoverflow'),
	'swiperFade': require('./swiper/swiperFade'),
	'swiperScrollbar': require('./swiper/swiperScrollbar'),
	'swiperGallery': require('./swiper/swiperGallery'),
	'swiperCustom': require('./swiper/swiperCustom'),
	'swiperParallax': require('./swiper/swiperParallax'),
	'swiperLazy': require('./swiper/swiperLazy'),

	//chat
	'login': require('./login/login'),
	'register': require('./login/register'),
	'messageInfo': require('./message/messageInfo'),
	'sendMultiMessage': require('./message/sendMultiMessage'),
	'contactInfo': require('./contact/contactInfo'),
	'selectUsers': require('./contact/selectUsers'),
	'audioCall': require('./call/audioCall'),
	'videoCall': require('./call/videoCall'),
	'groupList': require('./group/groupList'),
	'createGroup': require('./group/createGroup'),
	'searchGroup': require('./group/searchGroup'),
	'groupDetail': require('./group/groupDetail'),
	'searchGroupList': require('./group/searchGroupList'),
	'selectGroupUser': require('./group/searchGroup'),
   //icons
	'icons': require('./common/icons')
};
